@startuml

package "GUI Handler" {
    class ScreenManager {
        -sprites : List<Sprite>
        -mapper : ScreenMapper
        -settings : ScreenSettings
        +showSprites(sprites : List<Sprite>)
    }

    class ScreenMapper {
        +showSprites(sprites : List<Sprite>)
        +updateSprite(sprite : Sprite)
    }

    class ScreenSettings {
        soundVolume : Double
        musicVolume : Double
        language : String
        +getSoundVolume() : Double
        +setSoundVolume(volume : Double) : void
        +getMusicVolume() : Double
        +setMusicVolume(volume : Double) : void
        +getLanguage() : String
        +setLanguage(language : String) : void
        }

    ScreenManager o-- ScreenMapper : has
    ScreenManager --> ScreenSettings : uses settings
}

@enduml
