@startuml
package "Characters" {

  interface IRespawnable {
    + respawn(): void
  }

  abstract class AGhost {
    - origin: Position
   - sprite : Sprite
   - block : Block
   + {abstract} flee() : void
   + {abstract} chase(pacmanPosition: Position) : void
  }
  AGhost <|-- ClydeGhost
  AGhost <|-- PinkyGhost
  AGhost <|-- InkyGhost
  AGhost <|-- BlinkyGhost
  AGhost --> Block
  AGhost ..|> ACollisionHandler
  AGhost ..|> IRespawnable
  AGhost ..|> IUpdateSubscriber

  class Pacman {
   - sprite : Sprite
   - origin: Position
   - amountLives: int
   - block : Block
   - movement: Movement
   + hit() : bool
  }
  Pacman --> Block
  Pacman ..|> IRespawnable

  class Movement {
   - block : Block
   - up() : void
   - down() : void
   - left() : void
   - right() : void
  }
  Movement ..|> IProcessInputSubscriber
  Movement --o Pacman
}
@enduml

