@startuml
package "Collisions" {
  abstract class ACollisionHandler {
   + checkCollision(character : ICharacter, block : Block) : bool {abstract}
  }

  interface ICollisionHandler {
   + checkCollision(character : ICharacter, block : Block) : bool
  }
  ICollisionHandler ..|> ACollisionHandler

  class WallCollisionHandler {
   + checkCollision(character : ICharacter, block : Block) : bool
  }
  WallCollisionHandler ..|> ACollisionHandler

  class PacManCollisionHandler {
   + checkCollision(character : ICharacter, block : Block) : bool
  }
  PacManCollisionHandler ..|> ACollisionHandler

  class PowerSphereCollisionHandler {
   + checkCollision(character : ICharacter, block : Block) : bool
  }
  PowerSphereCollisionHandler ..|> ACollisionHandler

  class SphereCollisionHandler {
   + checkCollision(character : ICharacter, block : Block) : bool
  }
  SphereCollisionHandler ..|> ACollisionHandler
}
@enduml