@startuml
package "Collisions" {

  abstract class ACollisionHandler {
      + handleCollision() : void {abstract}
      + update() : void {abstract}
  }
  ACollisionHandler <|-- PacmanGhostCollisionHandler
  ACollisionHandler <|-- PacmanWallCollisionHandler
  ACollisionHandler <|-- PacmanSphereCollisionHandler
  ACollisionHandler <|-- PacmanPowerSphereCollisionHandler
  ACollisionHandler <|-- GhostWallCollisionHandler
  ACollisionHandler ..> UpdatePublisher

}
@enduml
