@startuml
package "Map" {
  class Block{
   - position : Position
  }

    class Maze {
   - blocks : Block[][]
   - pacman : Pacman
   - ghosts : AGhost[]
   + generateMaze() : void
  }
  Maze --> Block
  Maze --> Pacman
  Maze --> AGhost



  class Wall {
    - sprite : Sprite
      - position: Position
  }
  Wall --|> Block
  Wall --> Position : have
  Wall ..|> ACollisionHandler

  class Position {
   - x : int
   - y : int
  }

}
@enduml
