@startuml
package "Process Input Handler" {
!includesub ../../uml/frontend-software-system/process-input-handler.puml!INTERFACE
}
package "Render Handler" {
!includesub ../../uml/frontend-software-system/render-handler.puml!INTERFACE
}
!include ../../uml/frontend-software-system/game-settings.puml
package "Update Handler" {
!includesub ../../uml/frontend-software-system/update-handler.puml!INTERFACE
}

package Pac-Man {
!include collisions.puml
!include maze.puml
!include characters.puml

  class GameController {
   -maze : Maze
   -pacman : Pacman
   -ghosts : List<AGhost>
   -score : int
   -collisionHandler : ACollisionHandler
   + checkCollisions() : void
   + handleInput() : void
   + updateScore() : void
   + restart(): void
   + handleCollision(character : ICharacter, block : Block) : void
  }
  GameController ..> SoundFactory
  GameController ..> SpriteFactory
  GameController ..> ProcessInputPublisher: uses
  GameController ..|> IProcessInputSubscriber : implements
  GameController --> Pacman
  GameController --> AGhost
  GameController --> Maze
  GameController --|> AGameSettings : extends
  GameController --> ACollisionHandler

  interface ICollectable
  {
   + position: Position {get; set;}
   + collect(): void
  }

  ICollectable --> Position
  
  class PowerSphere {
   - sprite : Sprite
   - time : int
   + activatePower() : void
  }
  PowerSphere ..|> ICollectable
  PowerSphere ..|> ACollisionHandler
  PowerSphere --|> Block

  class Sphere {
   - sprite : Sprite
  }
  Sphere ..|> ICollectable
  Sphere --|> Block
  Sphere ..|> ACollisionHandler


}
@enduml
