@startuml
package "Process Input Handler" {
!includesub ../../uml/frontend-software-system/process-input-handler.puml!INTERFACE
}
package "Render Handler" {
!includesub ../../uml/frontend-software-system/render-handler.puml!INTERFACE
}
!include ../../uml/frontend-software-system/game-settings.puml
package "Update Handler" {
!includesub ../../uml/frontend-software-system/update-handler.puml!INTERFACE
}

package Pac-Man {
!include collisions.puml
!include maze.puml
!include characters.puml
!include collectables.puml
  class GameController {
   - pacman: Pacman
  }
  GameController ..> Pacman: <<uses>>
  GameController ..|> AGameSettings

  class GameInitializer {
    + init(): void
  }
  GameInitializer ..> GhostGenerator: <<creates>>
  GameInitializer ..> Maze: <<creates>>
  GameInitializer ..> CollectablesGenerator: <<creates>>
  GameInitializer ..> Pacman: <<instatiates>>
  GameInitializer ..> GameController: <<instatiates>>
  GameInitializer ..> SpriteFactory: <<uses>>
  GameInitializer ..> SoundFactory: <<uses>>
}

GameInitializer --( IIinitializerSubscriber: <<requires>>
@enduml

