@startuml input-listener-console
package "Console" {

    abstract class AEventListener {
        +handler: AEventHandler
        +native_listen(): List<String>
    }

    class KeyboardListener {
        +handler: AEventHandler
        +native_listen(): List<String>
    }

    class MouseListener {
        +handler: AEventHandler
        +native_listen(): List<String>
    }

    AEventListener <|-- KeyboardListener
    AEventListener <|-- MouseListener

    abstract class AEventHandler {
        -poolEvents: Vec<String>
        +handleEvent(): void
        +getPoolEvent(): Vec<String>
    }

    class KeyboardEventHandler {
        -poolEvents: Vec<String>
        +handleEvent(): void
        +getPoolEvent(): Vec<String>
    }

    class MouseEventHandler {
        -poolEvents: Vec<String>
        +handleEvent(): void
        +getPoolEvent(): Vec<String>
    }

    AEventHandler <|-- KeyboardEventHandler
    AEventHandler <|-- MouseEventHandler

    AEventListener *-- AEventHandler 

    class AppHandler {
        -eventHandlers: Vec<AEventHandler>
        +init(): void
    }

    AppHandler o-- AEventHandler  

}
@enduml
