@startuml
package "Game Loop" {
  class Game {
    -gameSettings : AGameSettings
    -inputVerifier : InputVerifier
    -updatePublisher : UpdatePublisher
    -renderManager : RenderManager

    -processInput() : void
    -update() : void
    -render() : void
    +run() : void
  }

  Game --> AGameSettings
  Game --> InputVerifier
  Game --> UpdatePublisher
  Game --> RenderManager
}
@enduml
