@startuml
package "Input Subscriptions" {
  interface ISubscriber {
    +notify(event : EventType) : void
  }

  class EventType {
    name : String
  }

  abstract class Handler {
    subscribers : <EventType, ISubscriber[]>
    +subscribe(event : EventType, subscriber : ISubscriber ) : void
  }
  Handler ..> EventType 
    Handler ..> ISubscriber
    Handler <|-- MouseSubscriber
    Handler <|-- KeyboardSubscriber
}
@enduml
