@startuml
package "Process Input Stage Subscriptions" {
  interface IProcessInputSubscriber {
    +notify(event : EventType) : void
  }

  class EventType {
    name : String
  }

  abstract class Handler {
    subscribers : <EventType, IProcessInputSubscriber[]>
    +subscribe(event : EventType, subscriber : IProcessInputSubscriber ) : void
  }
  Handler ..> EventType 
  Handler ..> IProcessInputSubscriber
  Handler <|-- MouseSubscriber
  Handler <|-- KeyboardSubscriber
}
@enduml
