@startuml
package ipc {
/'
------------------------------
Server
------------------------------
'/
    ' The channel
    class SocketServer {
        -receiver: Receiver
        +start(): void
        +stop(): void
    }
    SocketServer ..> Receiver: <<uses>>

    class Receiver {
        -keyboardBuffer: KeyboardInputPublisher
        -mouseBuffer: MouseInputPublisher
        ~handleMessage(rawMessage: ByteArray): void
    }
    Receiver ..> Event: <<creates>>
    Receiver ..> Buffer: <<uses>>

/'
------------------------------
Client
------------------------------
'/
    ' The channel
    class SocketClient {
        ~sendDataToServer(data: Frame, socketPath: String): void
    }

    class Transmitter {
        -socketClient: SocketClient
        +serializeToJson(frame: Frame): String
    }
    Transmitter ..> SocketClient: <<uses>>
}
@enduml

