@startuml
package "Render Handler" {
    class Coord {
        x : Integer
        y : Integer
    }

    class Size {
        height : Double
        width : Double
    }

    interface IFile {
        getPath() : String
    }

    class Sprite {
        position : Coord
        size : Size
        isHidden : boolean
    }
    Sprite --> Coord
    Sprite --> Size
    Sprite ..|> IFile

    class Sound {
        isPlaying: boolean
    }
    Sound ..|> IFile
}

@enduml