@startuml
package "Render Handler" {
    ' source
    class RenderManager {
        -transmitter: Transmitter
        -spriteRepository: SpriteRepository
        -SoundRepository: SoundRepository

        +renderSprites() : void
        +playSounds() : void
    }
    RenderManager ..> Transmitter: <<uses>>
    RenderManager ..> Frame: <<create>>
    RenderManager ..> SpriteRepository: <<uses>>
    RenderManager ..> SoundRepository: <<uses>>

    class SpriteRepository {
        -sprites: Sprite[]
        +addSprite(sprite: Sprite): void
        +getSprites(): Sprite[]
    }
    SpriteRepository "1" *-- "1..*" Sprite

    class SoundRepository {
        -sounds : Sound[]
        ~fetchPlayables(): Sound[]
        ~add(sound: Sound): void
    }
    SoundRepository "1" *-- "1..*" Sound

    interface ISpriteFactory {
        +createSprite() : Sprite
    }

!startsub INTERFACE
    class SpriteFactory  {
        -repository: SpriteRepository
        +createSprite(path: String): Sprite
    }

    class SoundFactory  {
        -repository: SoundRepository
        +createSound(path: String) : Sound
    }
!endsub
    SpriteFactory ..|> ISpriteFactory
    SpriteFactory ..> Sprite: <<creates>>
    SpriteFactory ..> SpriteRepository: <<use>>

    SoundFactory ..> Sound: <<creates>>
    SoundFactory ..> SoundRepository: <<use>>

    ' The message
    class Frame {
        -sounds: Sound[]
        -sprites: Sprite[]
    }
    Frame "1" *-- "1..*" Sprite
    Frame "1" *-- "1..*" Sound
}
@enduml

