@startuml
package "Render Handler" {
    ' source
    class RenderManager {
        -transmitter: Transmitter
        -spriteRenderer : SpriteRenderer
        -SoundRepository: SoundRepository

        +renderSprites() : void
        +playSounds() : void
    }
    RenderManager ..> Transmitter: <<uses>>
    RenderManager ..> Frame: <<create>>
    RenderManager o-- SpriteRenderer : uses
    RenderManager ..> SoundRepository: <<uses>>
    RenderManager o-- SpriteFactory : creates sprites

    class SpriteRenderer {
        -sprites : Sprite[]
        -spriteFactory : SpriteFactory

        +addSprite(sprite : Sprite) : void
        +removeSprite(sprite : Sprite) : void
        +updateSprite(sprite : Sprite, newSprite : Sprite) : void
        +renderSprite(sprite: Sprite) : void
    }
    SpriteRenderer *-- Sprite : manipulates

    class SoundRepository {
        -sounds : Sound[]
        ~fetchPlayables(): Sound[]
        ~add(sound: Sound): void
    }
    SoundRepository "1" *-- "1..*" Sound

    interface ISpriteFactory {
        +createSprite() : Sprite
    }

!startsub INTERFACE
    class SpriteFactory  {
        +createSprite() : Sprite
    }

    class SoundFactory  {
        -repository: SoundRepository
        +createSound(path: String) : Sound
    }
!endsub
    SpriteFactory ..|> ISpriteFactory

    SoundFactory  ..> Sound: <<creates>>
    SoundFactory  ..> SoundRepository: <<use>>

    ' The message
    class Frame {
        -sounds: Sound[]
        -sprites: Sprite[]
    }
    Frame "1" *-- "1..*" Sprite
    Frame "1" *-- "1..*" Sound
}
@enduml

