@startuml
package "Update Handler" {
!startsub INTERFACE
  interface IUpdateSubscriber {
    +notify() : void
  }

  class UpdatePublisher {
    -subscribers : IUpdateSubscriber[]
    +subscribe(subscriber : IUpdateSubscriber ) : void
    +notifySubscribers() : void
  }
  UpdatePublisher o-- IUpdateSubscriber
!endsub
}
@enduml
