@startuml
package "Update Handler" {
  interface IUpdateSubscriber {
    +notify() : void
  }

  class UpdatePublisher {
    -subscribers : IUpdateSubscriber[]
    +subscribe(subscriber : IUpdateSubscriber ) : void
  }
  UpdatePublisher o-- IUpdateSubscriber
}
@enduml
